name: Test-Build
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      api:        
        description: 'Collection to execute'
        default: 'jsonplaceholderapi'
        required: false

      environnement:
        description: 'Environnement'
        default: 'Preprod'
        required: false
     
      publishReport:
        description: 'PublishReport'
        default: true
        required: false

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install @types/newman --save
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-junitfull
          npm install -g newman-reporter-junitxray

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run collections/jsonplaceholderapi/postman_collection.json -e collections/jsonplaceholderapi/postman_environment.json -r 'cli,junitfull,junitxray,htmlextra' --reporter-htmlextra-export testResults/htmlreport.html  --reporter-junitfull-export testResults/postman_echo_junitfull.xml  --reporter-junitxray-export testResults/resultxray.xml

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
